title: Название вашей документации
description: Описание проекта
theme: just-the-docs

url: https://howto.pho.rs
baseurl: ""

# Настройки навигации
nav_enabled: true
nav_sort: case_insensitive

# Поиск
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/

# Внешние ссылки
aux_links:
  "GitHub":
    - "https://github.com/username/repository-name"

aux_links_new_tab: true

# Футер
footer_content: "Copyright &copy; 2024. Distributed under the MIT license."

# Цветовая схема (light, dark, или custom)
color_scheme: custom

# Кнопка "Back to top"
back_to_top: true
back_to_top_text: "Наверх"
